INCLUDES = \
		   includes/ast_generation.h \
		   includes/bleberr_macros.h \
		   includes/builtin_cd.h \
		   includes/builtin_echo.h \
		   includes/builtins.h \
		   includes/colors.h \
		   includes/env.h \
		   includes/execution.h \
		   includes/expander.h \
		   includes/g_builtin_array.h \
		   includes/g_shell_errmsg_array.h \
		   includes/g_shell_sigmodes.h \
		   includes/hashtable.h \
		   includes/history.h \
		   includes/input.h \
		   includes/heredoc_creation.h \
		   includes/io_redirect_settings.h \
		   includes/lexer.h \
		   includes/libbj.h \
		   includes/print_ast.h \
		   includes/redirection.h \
		   includes/s_container.h \
		   includes/s_fd_backup.h \
		   includes/shell.h \
		   includes/shell_ast/and_or.h \
		   includes/shell_ast/complete_command.h \
		   includes/shell_ast/container_labels.h \
		   includes/shell_ast/io_operator.h \
		   includes/shell_ast/io_redirect.h \
		   includes/shell_ast/list.h \
		   includes/shell_ast/pipe_sequence.h \
		   includes/shell_ast/pipeline.h \
		   includes/shell_ast/program.h \
		   includes/shell_ast/simple_command.h \
		   includes/shell_ast.h \
		   includes/shell_errmsg.h \
		   includes/shell_grammar.h \
		   includes/shell_pipe_sequence.h \
		   includes/shell_signal.h \
		   includes/term.h \
		   includes/tokens.h
