#!/bin/zsh

while [ $1 ] && [ $1 != "--" ]
do
	echo 1>&3 "void	*create_${1}(void const *lex_value);
t_bool	give_${1}(void *construct, void *sub_construct);";
	echo 1>&4 "void	delete_${1}(struct s_sh_${1} **const todel_loc);";
	shift;
done

if [ $1 ] && [ $1 = "--" ]
then
	shift;
fi

while [ $1 ]
do
	echo "t_bool create_$1(void *construct, void *sub_construct);";
	shift;
done
